import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../src/common/style/card.scss";
import "../src/common/style/global.scss";
import { ThemeProvider } from "@/src/common/providers/theme-provider";
import { soraSans } from "@/src/common/style/font";
import { cn } from "@/src/lib/utils";
import Navbar from "@/src/common/components/Navbar/Navbar";
import Footer from "@/src/common/components/footer";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={soraSans.className}>
        <Toaster />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="min-h-screen relative mx-auto px-6 sm:px-12 lg:max-w-[70rem] xl:max-w-[76rem] 2xl:max-w-[92rem] text-white">
            <Navbar />
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
